defaultPlacement: end
fieldLayouts:
  b7a9b51d-f18f-485f-84e1-b23ccabcefb1:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\TitleField
            uid: d6d59dd7-59f1-4735-a014-33312accb2d7
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 03c8ff50-fcd2-4bc3-8091-55edcfb7567a
        userCondition: null
handle: drivingLicenses
name: 'Driving Licenses'
siteSettings:
  5da841b1-ca0d-46ff-8bb1-04d6c889ac54: # English
    hasUrls: false
    template: null
    uriFormat: null
  ec473f07-152f-423b-90df-ac425e6068a1: # Spanish
    hasUrls: false
    template: null
    uriFormat: null
structure:
  maxLevels: null
  uid: da5a8c32-6b64-4f21-a5fd-4b7af57f0db8
