defaultPlacement: end
fieldLayouts:
  2de041eb-c856-4dc5-b30e-e3b565a28af9:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\TitleField
            uid: ec250efd-6810-44f8-93ad-7ca26627a3e7
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 771dfe90-8b41-4322-908d-890e0bd72900
        userCondition: null
handle: shifts
name: Shifts
siteSettings:
  5da841b1-ca0d-46ff-8bb1-04d6c889ac54: # English
    hasUrls: false
    template: null
    uriFormat: null
  ec473f07-152f-423b-90df-ac425e6068a1: # Spanish
    hasUrls: false
    template: null
    uriFormat: null
structure:
  maxLevels: null
  uid: 84a0209b-8ca8-48c1-9b67-ef9541111f05
