defaultPlacement: end
fieldLayouts:
  4fe1852d-7b8c-4ea9-8266-8936a20c7d01:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\TitleField
            uid: 23c5d995-aa81-4b23-8452-d578fd111d0d
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 18a7b7ef-6af0-4450-9886-304ed7f4ce1f
        userCondition: null
handle: workRegimes
name: 'Work Regimes'
siteSettings:
  5da841b1-ca0d-46ff-8bb1-04d6c889ac54: # English
    hasUrls: false
    template: null
    uriFormat: null
  ec473f07-152f-423b-90df-ac425e6068a1: # Spanish
    hasUrls: false
    template: null
    uriFormat: null
structure:
  maxLevels: null
  uid: 4fc296ac-868c-47a0-ae75-a58334463bf9
