defaultPlacement: end
enableVersioning: true
entryTypes:
  - 901e615c-d5d1-4bcd-b6d6-e2e1d3d78689 # Job
handle: jobs
maxAuthors: 1
name: Jobs
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  5da841b1-ca0d-46ff-8bb1-04d6c889ac54: # English
    enabledByDefault: true
    hasUrls: true
    template: jobs/_entry
    uriFormat: 'jobs/{slug}'
type: channel
