color: null
fieldLayouts:
  38832b2a-c586-4bba-8d07-fce30a3357a2:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 65e0072b-ab30-4c7f-96d0-8fef8aa45ce6
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: c035276a-67e5-4da5-8c87-b39f18cd971f # Communication Type
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 908e2982-9c77-4332-a072-d796b1c3a50d
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: 35cc7afb-4ec8-4528-b383-c58705da22ae # Contact
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: b9dec1c3-29e4-468c-9b32-305d60c3b0b2
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: bf32dca0-775d-4836-a59f-5129e3aa284b # Telephone
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 1d100d11-2a91-4a9c-ba98-802b9f57e0a4
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: aecd54da-242a-4e38-9e6d-00bb8a914e21 # Email address
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: d64940fa-d34c-4a9b-a6d9-1a7e1ac4c955
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 96f0c7c2-0180-4a10-82e2-cdab9fb2dc3b
        userCondition: null
handle: communication
hasTitleField: false
icon: ''
name: Communication
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: ''
slugTranslationMethod: site
titleFormat: '{communicationType.label}: {emailAddress}{telephone}{contact}'
titleTranslationKeyFormat: ''
titleTranslationMethod: site
