color: null
fieldLayouts:
  1cf7e6c7-c7a6-4f22-afd7-b2a5221cc7f4:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 6a41100e-ab24-42eb-9bc3-8a8ef3b38f20
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 8f588de3-6d91-4446-af78-41fca2828740
        userCondition: null
handle: license
hasTitleField: true
icon: ''
name: License
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: ''
slugTranslationMethod: site
titleFormat: ''
titleTranslationKeyFormat: ''
titleTranslationMethod: site
