columnSuffix: null
handle: offer
instructions: null
name: Offer
searchable: false
settings:
  availableTransforms: ''
  availableVolumes: '*'
  ckeConfig: b1904d35-094d-4bbe-83ce-5b154fbc0cfc # Full
  createButtonLabel: null
  defaultTransform: null
  enableSourceEditingForNonAdmins: false
  purifierConfig: null
  purifyHtml: true
  showUnpermittedFiles: false
  showUnpermittedVolumes: false
  showWordCount: false
  wordLimit: null
translationKeyFormat: null
translationMethod: none
type: craft\ckeditor\Field
